version: '3'
services:
  minio-service:
    image: quay.io/minio/minio
    ports:
      - '9000:9000'
      - '9090:9090'
    volumes:
      - ~/minio/data:/data
    environment:
      - MINIO_ROOT_USER=my_secret_username
      - MINIO_ROOT_PASSWORD=stong_secret_password
    command: server /data --console-address ":9090"
